on:
  workflow_call:
    inputs:
      sha:
        type: string
        required: true


jobs:
  build:
    name: Build & push deploy Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build & push
        run: |
          docker build --tag mkakpabla/laravel-ci-cd:${{  github.ref_name }} .
          docker push mkakpabla/laravel-ci-cd:${{  github.ref_name }}