on:
  workflow_call:
    inputs:
      sha:
        type: string
        required: true

jobs:
  build:
    name: Build Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: bcmath, bz2, calendar, intl, mbstring, pdo_mysql, gd, exif, zip, sodium

      - name: Composer install
        run: composer install --no-interaction --no-progress

      - name: Create Artefact
        env:
          GITHUB_SHA: ${{ inputs.sha }}
        run: tar -czf "${GITHUB_SHA}".tar.gz --exclude=*.git --exclude=node_modules --exclude=.github *

      - uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: ./${{ inputs.sha }}.tar.gz
          retention-days: 0

  pint:
    name: pint
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-build
          path: ./

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: bcmath, bz2, calendar, intl, mbstring, pdo_mysql, gd, exif, zip, sodium

      - name: Extract Artefact
        run: tar -xzf ./${{ inputs.sha }}.tar.gz -C .
      - name: Execute Pint Test
        run: composer pint-test

  phpmd:
    name: phpmd
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-build
          path: ./

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: bcmath, bz2, calendar, intl, mbstring, pdo_mysql, gd, exif, zip, sodium

      - name: Extract Artefact
        run: tar -xzf ./${{ inputs.sha }}.tar.gz -C .
      - name: Execute PHPMD
        run: composer phpmd

  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-build
          path: ./

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: bcmath, bz2, calendar, intl, mbstring, pdo_mysql, gd, exif, zip, sodium

      - name: Extract Artefact
        run: tar -xzf ./${{ inputs.sha }}.tar.gz -C .
      - name: Execute phpstan
        run: composer phpstan