name: Pull Request
on:
  pull_request:
    branches:
      - '*'

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
    with:
      sha: ${{ github.sha }}

  clean-up:
    name: Delete Artifact
    runs-on: ubuntu-latest
    needs: [ci]
    if: ${{ always() }}
    steps:
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: app-build